/*
 * This file is generated by jOOQ.
*/
package media.thehoard.common.database.jooq;


import javax.annotation.Generated;

import media.thehoard.common.database.jooq.routines.Revokeauthentication;

import org.jooq.Configuration;
import org.jooq.Field;


/**
 * Convenience access to all stored procedures and functions in thehoard
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Routines {

    /**
     * Call <code>thehoard.revokeAuthentication</code>
     */
    public static Integer revokeauthentication(Configuration configuration, Integer authid) {
        Revokeauthentication f = new Revokeauthentication();
        f.setAuthid(authid);

        f.execute(configuration);
        return f.getReturnValue();
    }

    /**
     * Get <code>thehoard.revokeAuthentication</code> as a field.
     */
    public static Field<Integer> revokeauthentication(Integer authid) {
        Revokeauthentication f = new Revokeauthentication();
        f.setAuthid(authid);

        return f.asField();
    }

    /**
     * Get <code>thehoard.revokeAuthentication</code> as a field.
     */
    public static Field<Integer> revokeauthentication(Field<Integer> authid) {
        Revokeauthentication f = new Revokeauthentication();
        f.setAuthid(authid);

        return f.asField();
    }
}
