/*
 * This file is generated by jOOQ.
*/
package media.thehoard.common.database.jooq;


import javax.annotation.Generated;

import media.thehoard.common.database.jooq.tables.Accounts;
import media.thehoard.common.database.jooq.tables.Authentication;
import media.thehoard.common.database.jooq.tables.Devices;
import media.thehoard.common.database.jooq.tables.Distributordestinations;
import media.thehoard.common.database.jooq.tables.Distributordirectories;
import media.thehoard.common.database.jooq.tables.Distributorqueue;
import media.thehoard.common.database.jooq.tables.Homeaccounts;
import media.thehoard.common.database.jooq.tables.Homes;
import media.thehoard.common.database.jooq.tables.Mediachapters;
import media.thehoard.common.database.jooq.tables.Mediafiles;
import media.thehoard.common.database.jooq.tables.Mediastreams;
import media.thehoard.common.database.jooq.tables.Parties;
import media.thehoard.common.database.jooq.tables.Partyaccounts;
import media.thehoard.common.database.jooq.tables.Providerfilerelationships;
import media.thehoard.common.database.jooq.tables.Providerfiles;
import media.thehoard.common.database.jooq.tables.Providers;
import media.thehoard.common.database.jooq.tables.Providersold;
import media.thehoard.common.database.jooq.tables.Servers;
import media.thehoard.common.database.jooq.tables.Virtualproviderproviders;
import media.thehoard.common.database.jooq.tables.Virtualproviders;


/**
 * Convenience access to all tables in thehoard
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>thehoard.Accounts</code>.
     */
    public static final Accounts ACCOUNTS = media.thehoard.common.database.jooq.tables.Accounts.ACCOUNTS;

    /**
     * The table <code>thehoard.Authentication</code>.
     */
    public static final Authentication AUTHENTICATION = media.thehoard.common.database.jooq.tables.Authentication.AUTHENTICATION;

    /**
     * The table <code>thehoard.devices</code>.
     */
    public static final Devices DEVICES = media.thehoard.common.database.jooq.tables.Devices.DEVICES;

    /**
     * The table <code>thehoard.distributorDestinations</code>.
     */
    public static final Distributordestinations DISTRIBUTORDESTINATIONS = media.thehoard.common.database.jooq.tables.Distributordestinations.DISTRIBUTORDESTINATIONS;

    /**
     * This table stores all the directories for each destination, to prevent constant API hits to parse destinations.
This is structured differently than the regular files/directories tables because it doesn't use foreign keys.
     */
    public static final Distributordirectories DISTRIBUTORDIRECTORIES = media.thehoard.common.database.jooq.tables.Distributordirectories.DISTRIBUTORDIRECTORIES;

    /**
     * The table <code>thehoard.distributorQueue</code>.
     */
    public static final Distributorqueue DISTRIBUTORQUEUE = media.thehoard.common.database.jooq.tables.Distributorqueue.DISTRIBUTORQUEUE;

    /**
     * The table <code>thehoard.HomeAccounts</code>.
     */
    public static final Homeaccounts HOMEACCOUNTS = media.thehoard.common.database.jooq.tables.Homeaccounts.HOMEACCOUNTS;

    /**
     * The table <code>thehoard.Homes</code>.
     */
    public static final Homes HOMES = media.thehoard.common.database.jooq.tables.Homes.HOMES;

    /**
     * The table <code>thehoard.MediaChapters</code>.
     */
    public static final Mediachapters MEDIACHAPTERS = media.thehoard.common.database.jooq.tables.Mediachapters.MEDIACHAPTERS;

    /**
     * The table <code>thehoard.MediaFiles</code>.
     */
    public static final Mediafiles MEDIAFILES = media.thehoard.common.database.jooq.tables.Mediafiles.MEDIAFILES;

    /**
     * The table <code>thehoard.MediaStreams</code>.
     */
    public static final Mediastreams MEDIASTREAMS = media.thehoard.common.database.jooq.tables.Mediastreams.MEDIASTREAMS;

    /**
     * The table <code>thehoard.Parties</code>.
     */
    public static final Parties PARTIES = media.thehoard.common.database.jooq.tables.Parties.PARTIES;

    /**
     * The table <code>thehoard.PartyAccounts</code>.
     */
    public static final Partyaccounts PARTYACCOUNTS = media.thehoard.common.database.jooq.tables.Partyaccounts.PARTYACCOUNTS;

    /**
     * The table <code>thehoard.ProviderFileRelationships</code>.
     */
    public static final Providerfilerelationships PROVIDERFILERELATIONSHIPS = media.thehoard.common.database.jooq.tables.Providerfilerelationships.PROVIDERFILERELATIONSHIPS;

    /**
     * The table <code>thehoard.ProviderFiles</code>.
     */
    public static final Providerfiles PROVIDERFILES = media.thehoard.common.database.jooq.tables.Providerfiles.PROVIDERFILES;

    /**
     * The table <code>thehoard.Providers</code>.
     */
    public static final Providers PROVIDERS = media.thehoard.common.database.jooq.tables.Providers.PROVIDERS;

    /**
     * The table <code>thehoard.providersold</code>.
     */
    public static final Providersold PROVIDERSOLD = media.thehoard.common.database.jooq.tables.Providersold.PROVIDERSOLD;

    /**
     * The table <code>thehoard.servers</code>.
     */
    public static final Servers SERVERS = media.thehoard.common.database.jooq.tables.Servers.SERVERS;

    /**
     * Provider references for virtual providers
     */
    public static final Virtualproviderproviders VIRTUALPROVIDERPROVIDERS = media.thehoard.common.database.jooq.tables.Virtualproviderproviders.VIRTUALPROVIDERPROVIDERS;

    /**
     * Virtual provider structures used for spanning across multiple providers
     */
    public static final Virtualproviders VIRTUALPROVIDERS = media.thehoard.common.database.jooq.tables.Virtualproviders.VIRTUALPROVIDERS;
}
