/*
 * This file is generated by jOOQ.
*/
package media.thehoard.common.database.jooq.tables.records;


import javax.annotation.Generated;

import media.thehoard.common.database.jooq.tables.Mediachapters;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MediachaptersRecord extends UpdatableRecordImpl<MediachaptersRecord> implements Record8<Integer, String, String, Long, Double, Double, Double, String> {

    private static final long serialVersionUID = -309111062;

    /**
     * Setter for <code>thehoard.MediaChapters.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>thehoard.MediaChapters.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thehoard.MediaChapters.Uuid</code>.
     */
    public void setUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>thehoard.MediaChapters.Uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thehoard.MediaChapters.MediaFileUuid</code>.
     */
    public void setMediafileuuid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>thehoard.MediaChapters.MediaFileUuid</code>.
     */
    public String getMediafileuuid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thehoard.MediaChapters.ChapterId</code>.
     */
    public void setChapterid(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>thehoard.MediaChapters.ChapterId</code>.
     */
    public Long getChapterid() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>thehoard.MediaChapters.TimeBase</code>.
     */
    public void setTimebase(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>thehoard.MediaChapters.TimeBase</code>.
     */
    public Double getTimebase() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>thehoard.MediaChapters.Start</code>.
     */
    public void setStart(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>thehoard.MediaChapters.Start</code>.
     */
    public Double getStart() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>thehoard.MediaChapters.End</code>.
     */
    public void setEnd(Double value) {
        set(6, value);
    }

    /**
     * Getter for <code>thehoard.MediaChapters.End</code>.
     */
    public Double getEnd() {
        return (Double) get(6);
    }

    /**
     * Setter for <code>thehoard.MediaChapters.Title</code>.
     */
    public void setTitle(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>thehoard.MediaChapters.Title</code>.
     */
    public String getTitle() {
        return (String) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Long, Double, Double, Double, String> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Long, Double, Double, Double, String> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Mediachapters.MEDIACHAPTERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Mediachapters.MEDIACHAPTERS.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Mediachapters.MEDIACHAPTERS.MEDIAFILEUUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return Mediachapters.MEDIACHAPTERS.CHAPTERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Mediachapters.MEDIACHAPTERS.TIMEBASE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Mediachapters.MEDIACHAPTERS.START;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field7() {
        return Mediachapters.MEDIACHAPTERS.END;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Mediachapters.MEDIACHAPTERS.TITLE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getMediafileuuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getChapterid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getTimebase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component7() {
        return getEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getMediafileuuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getChapterid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getTimebase();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getStart();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value7() {
        return getEnd();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getTitle();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediachaptersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediachaptersRecord value2(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediachaptersRecord value3(String value) {
        setMediafileuuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediachaptersRecord value4(Long value) {
        setChapterid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediachaptersRecord value5(Double value) {
        setTimebase(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediachaptersRecord value6(Double value) {
        setStart(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediachaptersRecord value7(Double value) {
        setEnd(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediachaptersRecord value8(String value) {
        setTitle(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MediachaptersRecord values(Integer value1, String value2, String value3, Long value4, Double value5, Double value6, Double value7, String value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MediachaptersRecord
     */
    public MediachaptersRecord() {
        super(Mediachapters.MEDIACHAPTERS);
    }

    /**
     * Create a detached, initialised MediachaptersRecord
     */
    public MediachaptersRecord(Integer id, String uuid, String mediafileuuid, Long chapterid, Double timebase, Double start, Double end, String title) {
        super(Mediachapters.MEDIACHAPTERS);

        set(0, id);
        set(1, uuid);
        set(2, mediafileuuid);
        set(3, chapterid);
        set(4, timebase);
        set(5, start);
        set(6, end);
        set(7, title);
    }
}
