/*
 * This file is generated by jOOQ.
*/
package media.thehoard.common.database.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartyaccountsRecord extends UpdatableRecordImpl<PartyaccountsRecord> implements Record7<Integer, Integer, Integer, Byte, Timestamp, Timestamp, Timestamp> {

    private static final long serialVersionUID = -1319355579;

    /**
     * Setter for <code>thehoard.PartyAccounts.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>thehoard.PartyAccounts.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thehoard.PartyAccounts.accountId</code>.
     */
    public void setAccountid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>thehoard.PartyAccounts.accountId</code>.
     */
    public Integer getAccountid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>thehoard.PartyAccounts.partyId</code>.
     */
    public void setPartyid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>thehoard.PartyAccounts.partyId</code>.
     */
    public Integer getPartyid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>thehoard.PartyAccounts.isActive</code>.
     */
    public void setIsactive(Byte value) {
        set(3, value);
    }

    /**
     * Getter for <code>thehoard.PartyAccounts.isActive</code>.
     */
    public Byte getIsactive() {
        return (Byte) get(3);
    }

    /**
     * Setter for <code>thehoard.PartyAccounts.dateJoined</code>.
     */
    public void setDatejoined(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>thehoard.PartyAccounts.dateJoined</code>.
     */
    public Timestamp getDatejoined() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>thehoard.PartyAccounts.dateUpdated</code>.
     */
    public void setDateupdated(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>thehoard.PartyAccounts.dateUpdated</code>.
     */
    public Timestamp getDateupdated() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>thehoard.PartyAccounts.dateLeft</code>.
     */
    public void setDateleft(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>thehoard.PartyAccounts.dateLeft</code>.
     */
    public Timestamp getDateleft() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Byte, Timestamp, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, Integer, Byte, Timestamp, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Partyaccounts.PARTYACCOUNTS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Partyaccounts.PARTYACCOUNTS.ACCOUNTID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Partyaccounts.PARTYACCOUNTS.PARTYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field4() {
        return Partyaccounts.PARTYACCOUNTS.ISACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Partyaccounts.PARTYACCOUNTS.DATEJOINED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Partyaccounts.PARTYACCOUNTS.DATEUPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Partyaccounts.PARTYACCOUNTS.DATELEFT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getAccountid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getPartyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component4() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getDatejoined();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getDateupdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDateleft();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getAccountid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getPartyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value4() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getDatejoined();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDateupdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDateleft();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyaccountsRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyaccountsRecord value2(Integer value) {
        setAccountid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyaccountsRecord value3(Integer value) {
        setPartyid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyaccountsRecord value4(Byte value) {
        setIsactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyaccountsRecord value5(Timestamp value) {
        setDatejoined(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyaccountsRecord value6(Timestamp value) {
        setDateupdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyaccountsRecord value7(Timestamp value) {
        setDateleft(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PartyaccountsRecord values(Integer value1, Integer value2, Integer value3, Byte value4, Timestamp value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PartyaccountsRecord
     */
    public PartyaccountsRecord() {
        super(Partyaccounts.PARTYACCOUNTS);
    }

    /**
     * Create a detached, initialised PartyaccountsRecord
     */
    public PartyaccountsRecord(Integer id, Integer accountid, Integer partyid, Byte isactive, Timestamp datejoined, Timestamp dateupdated, Timestamp dateleft) {
        super(Partyaccounts.PARTYACCOUNTS);

        set(0, id);
        set(1, accountid);
        set(2, partyid);
        set(3, isactive);
        set(4, datejoined);
        set(5, dateupdated);
        set(6, dateleft);
    }
}
