/*
 * This file is generated by jOOQ.
*/
package media.thehoard.common.database.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import media.thehoard.hoardmediaserver.common.database.jooq.tables.Providers;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record13;
import org.jooq.Row13;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProvidersRecord extends UpdatableRecordImpl<ProvidersRecord> implements Record13<Integer, String, String, String, Byte, Byte, Byte, Timestamp, Timestamp, String, String, String, byte[]> {

    private static final long serialVersionUID = 261743286;

    /**
     * Setter for <code>thehoard.Providers.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>thehoard.Providers.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thehoard.Providers.Uuid</code>.
     */
    public void setUuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>thehoard.Providers.Uuid</code>.
     */
    public String getUuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thehoard.Providers.Alias</code>.
     */
    public void setAlias(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>thehoard.Providers.Alias</code>.
     */
    public String getAlias() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thehoard.Providers.ProviderAlias</code>.
     */
    public void setProvideralias(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>thehoard.Providers.ProviderAlias</code>.
     */
    public String getProvideralias() {
        return (String) get(3);
    }

    /**
     * Setter for <code>thehoard.Providers.TypeId</code>.
     */
    public void setTypeid(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>thehoard.Providers.TypeId</code>.
     */
    public Byte getTypeid() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>thehoard.Providers.UsageId</code>.
     */
    public void setUsageid(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>thehoard.Providers.UsageId</code>.
     */
    public Byte getUsageid() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>thehoard.Providers.Status</code>.
     */
    public void setStatus(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>thehoard.Providers.Status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(6);
    }

    /**
     * Setter for <code>thehoard.Providers.DateCreated</code>.
     */
    public void setDatecreated(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>thehoard.Providers.DateCreated</code>.
     */
    public Timestamp getDatecreated() {
        return (Timestamp) get(7);
    }

    /**
     * Setter for <code>thehoard.Providers.DateUpdated</code>.
     */
    public void setDateupdated(Timestamp value) {
        set(8, value);
    }

    /**
     * Getter for <code>thehoard.Providers.DateUpdated</code>.
     */
    public Timestamp getDateupdated() {
        return (Timestamp) get(8);
    }

    /**
     * Setter for <code>thehoard.Providers.Configuration</code>.
     */
    public void setConfiguration(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>thehoard.Providers.Configuration</code>.
     */
    public String getConfiguration() {
        return (String) get(9);
    }

    /**
     * Setter for <code>thehoard.Providers.Credential</code>.
     */
    public void setCredential(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>thehoard.Providers.Credential</code>.
     */
    public String getCredential() {
        return (String) get(10);
    }

    /**
     * Setter for <code>thehoard.Providers.ChangeToken</code>.
     */
    public void setChangetoken(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>thehoard.Providers.ChangeToken</code>.
     */
    public String getChangetoken() {
        return (String) get(11);
    }

    /**
     * Setter for <code>thehoard.Providers.OldCredential</code>.
     */
    public void setOldcredential(byte... value) {
        set(12, value);
    }

    /**
     * Getter for <code>thehoard.Providers.OldCredential</code>.
     */
    public byte[] getOldcredential() {
        return (byte[]) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record13 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, Byte, Byte, Byte, Timestamp, Timestamp, String, String, String, byte[]> fieldsRow() {
        return (Row13) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row13<Integer, String, String, String, Byte, Byte, Byte, Timestamp, Timestamp, String, String, String, byte[]> valuesRow() {
        return (Row13) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Providers.PROVIDERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Providers.PROVIDERS.UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Providers.PROVIDERS.ALIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Providers.PROVIDERS.PROVIDERALIAS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Providers.PROVIDERS.TYPEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field6() {
        return Providers.PROVIDERS.USAGEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Providers.PROVIDERS.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Providers.PROVIDERS.DATECREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field9() {
        return Providers.PROVIDERS.DATEUPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Providers.PROVIDERS.CONFIGURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Providers.PROVIDERS.CREDENTIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field12() {
        return Providers.PROVIDERS.CHANGETOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<byte[]> field13() {
        return Providers.PROVIDERS.OLDCREDENTIAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getProvideralias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getTypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component6() {
        return getUsageid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getDatecreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component9() {
        return getDateupdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getConfiguration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getCredential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component12() {
        return getChangetoken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] component13() {
        return getOldcredential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getAlias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getProvideralias();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getTypeid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value6() {
        return getUsageid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getDatecreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value9() {
        return getDateupdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getConfiguration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getCredential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value12() {
        return getChangetoken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public byte[] value13() {
        return getOldcredential();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value2(String value) {
        setUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value3(String value) {
        setAlias(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value4(String value) {
        setProvideralias(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value5(Byte value) {
        setTypeid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value6(Byte value) {
        setUsageid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value7(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value8(Timestamp value) {
        setDatecreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value9(Timestamp value) {
        setDateupdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value10(String value) {
        setConfiguration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value11(String value) {
        setCredential(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value12(String value) {
        setChangetoken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord value13(byte... value) {
        setOldcredential(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProvidersRecord values(Integer value1, String value2, String value3, String value4, Byte value5, Byte value6, Byte value7, Timestamp value8, Timestamp value9, String value10, String value11, String value12, byte[] value13) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProvidersRecord
     */
    public ProvidersRecord() {
        super(Providers.PROVIDERS);
    }

    /**
     * Create a detached, initialised ProvidersRecord
     */
    public ProvidersRecord(Integer id, String uuid, String alias, String provideralias, Byte typeid, Byte usageid, Byte status, Timestamp datecreated, Timestamp dateupdated, String configuration, String credential, String changetoken, byte[] oldcredential) {
        super(Providers.PROVIDERS);

        set(0, id);
        set(1, uuid);
        set(2, alias);
        set(3, provideralias);
        set(4, typeid);
        set(5, usageid);
        set(6, status);
        set(7, datecreated);
        set(8, dateupdated);
        set(9, configuration);
        set(10, credential);
        set(11, changetoken);
        set(12, oldcredential);
    }
}
