/*
 * This file is generated by jOOQ.
 */
package com.atherapp.common.database.jooq;


import com.atherapp.common.database.jooq.tables.*;
import com.atherapp.common.database.jooq.tables.records.*;
import com.atherapp.common.database.jooq.tables.*;
import com.atherapp.common.database.jooq.tables.records.*;
import org.jooq.Identity;
import org.jooq.UniqueKey;
import org.jooq.impl.AbstractKeys;

import javax.annotation.Generated;


/**
 * A class modelling foreign key relationships and constraints of tables of
 * the <code>thehoard</code> schema.
 */
@Generated(value = {"http://www.jooq.org", "jOOQ version:3.10.1"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final Identity<DevicesRecord, Integer> IDENTITY_DEVICES = Identities0.IDENTITY_DEVICES;
	public static final Identity<DistributordestinationsRecord, Integer> IDENTITY_DISTRIBUTORDESTINATIONS = Identities0.IDENTITY_DISTRIBUTORDESTINATIONS;
	public static final Identity<DistributordirectoriesRecord, Integer> IDENTITY_DISTRIBUTORDIRECTORIES = Identities0.IDENTITY_DISTRIBUTORDIRECTORIES;
	public static final Identity<DistributorqueueRecord, Integer> IDENTITY_DISTRIBUTORQUEUE = Identities0.IDENTITY_DISTRIBUTORQUEUE;
	public static final Identity<HomesRecord, Integer> IDENTITY_HOMES = Identities0.IDENTITY_HOMES;
	public static final Identity<MediachaptersRecord, Integer> IDENTITY_MEDIACHAPTERS = Identities0.IDENTITY_MEDIACHAPTERS;
	public static final Identity<MediafilesRecord, Integer> IDENTITY_MEDIAFILES = Identities0.IDENTITY_MEDIAFILES;
	public static final Identity<MediastreamsRecord, Integer> IDENTITY_MEDIASTREAMS = Identities0.IDENTITY_MEDIASTREAMS;
	public static final Identity<ProviderfilerelationshipsRecord, Integer> IDENTITY_PROVIDERFILERELATIONSHIPS = Identities0.IDENTITY_PROVIDERFILERELATIONSHIPS;
	public static final Identity<ProviderfilesRecord, Integer> IDENTITY_PROVIDERFILES = Identities0.IDENTITY_PROVIDERFILES;
	public static final Identity<ProvidersRecord, Integer> IDENTITY_PROVIDERS = Identities0.IDENTITY_PROVIDERS;
	public static final Identity<ProvidersoldRecord, Integer> IDENTITY_PROVIDERSOLD = Identities0.IDENTITY_PROVIDERSOLD;
	public static final Identity<ServersRecord, Integer> IDENTITY_SERVERS = Identities0.IDENTITY_SERVERS;
	public static final Identity<VirtualproviderprovidersRecord, Integer> IDENTITY_VIRTUALPROVIDERPROVIDERS = Identities0.IDENTITY_VIRTUALPROVIDERPROVIDERS;
	public static final Identity<VirtualprovidersRecord, Integer> IDENTITY_VIRTUALPROVIDERS = Identities0.IDENTITY_VIRTUALPROVIDERS;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final UniqueKey<AuthenticationRecord> KEY_AUTHENTICATION_PRIMARY = UniqueKeys0.KEY_AUTHENTICATION_PRIMARY;
	public static final UniqueKey<AuthenticationRecord> KEY_AUTHENTICATION_ID_UNIQUE = UniqueKeys0.KEY_AUTHENTICATION_ID_UNIQUE;
	public static final UniqueKey<DevicesRecord> KEY_DEVICES_PRIMARY = UniqueKeys0.KEY_DEVICES_PRIMARY;
	public static final UniqueKey<DevicesRecord> KEY_DEVICES_ID_UNIQUE = UniqueKeys0.KEY_DEVICES_ID_UNIQUE;
	public static final UniqueKey<DistributordestinationsRecord> KEY_DISTRIBUTORDESTINATIONS_PRIMARY = UniqueKeys0.KEY_DISTRIBUTORDESTINATIONS_PRIMARY;
	public static final UniqueKey<DistributordestinationsRecord> KEY_DISTRIBUTORDESTINATIONS_ID_UNIQUE = UniqueKeys0.KEY_DISTRIBUTORDESTINATIONS_ID_UNIQUE;
	public static final UniqueKey<DistributordirectoriesRecord> KEY_DISTRIBUTORDIRECTORIES_PRIMARY = UniqueKeys0.KEY_DISTRIBUTORDIRECTORIES_PRIMARY;
	public static final UniqueKey<DistributordirectoriesRecord> KEY_DISTRIBUTORDIRECTORIES_ID_UNIQUE = UniqueKeys0.KEY_DISTRIBUTORDIRECTORIES_ID_UNIQUE;
	public static final UniqueKey<DistributorqueueRecord> KEY_DISTRIBUTORQUEUE_PRIMARY = UniqueKeys0.KEY_DISTRIBUTORQUEUE_PRIMARY;
	public static final UniqueKey<DistributorqueueRecord> KEY_DISTRIBUTORQUEUE_ID_UNIQUE = UniqueKeys0.KEY_DISTRIBUTORQUEUE_ID_UNIQUE;
	public static final UniqueKey<HomeaccountsRecord> KEY_HOMEACCOUNTS_PRIMARY = UniqueKeys0.KEY_HOMEACCOUNTS_PRIMARY;
	public static final UniqueKey<HomeaccountsRecord> KEY_HOMEACCOUNTS_ID_UNIQUE = UniqueKeys0.KEY_HOMEACCOUNTS_ID_UNIQUE;
	public static final UniqueKey<HomesRecord> KEY_HOMES_PRIMARY = UniqueKeys0.KEY_HOMES_PRIMARY;
	public static final UniqueKey<HomesRecord> KEY_HOMES_ID_UNIQUE = UniqueKeys0.KEY_HOMES_ID_UNIQUE;
	public static final UniqueKey<MediachaptersRecord> KEY_MEDIACHAPTERS_PRIMARY = UniqueKeys0.KEY_MEDIACHAPTERS_PRIMARY;
	public static final UniqueKey<MediachaptersRecord> KEY_MEDIACHAPTERS_ID_UNIQUE = UniqueKeys0.KEY_MEDIACHAPTERS_ID_UNIQUE;
	public static final UniqueKey<MediachaptersRecord> KEY_MEDIACHAPTERS_UUID_UNIQUE = UniqueKeys0.KEY_MEDIACHAPTERS_UUID_UNIQUE;
	public static final UniqueKey<MediafilesRecord> KEY_MEDIAFILES_PRIMARY = UniqueKeys0.KEY_MEDIAFILES_PRIMARY;
	public static final UniqueKey<MediafilesRecord> KEY_MEDIAFILES_ID_UNIQUE = UniqueKeys0.KEY_MEDIAFILES_ID_UNIQUE;
	public static final UniqueKey<MediafilesRecord> KEY_MEDIAFILES_UUID_UNIQUE = UniqueKeys0.KEY_MEDIAFILES_UUID_UNIQUE;
	public static final UniqueKey<MediastreamsRecord> KEY_MEDIASTREAMS_PRIMARY = UniqueKeys0.KEY_MEDIASTREAMS_PRIMARY;
	public static final UniqueKey<MediastreamsRecord> KEY_MEDIASTREAMS_ID_UNIQUE = UniqueKeys0.KEY_MEDIASTREAMS_ID_UNIQUE;
	public static final UniqueKey<MediastreamsRecord> KEY_MEDIASTREAMS_UUID_UNIQUE = UniqueKeys0.KEY_MEDIASTREAMS_UUID_UNIQUE;
	public static final UniqueKey<PartiesRecord> KEY_PARTIES_PRIMARY = UniqueKeys0.KEY_PARTIES_PRIMARY;
	public static final UniqueKey<PartiesRecord> KEY_PARTIES_ID_UNIQUE = UniqueKeys0.KEY_PARTIES_ID_UNIQUE;
	public static final UniqueKey<PartyaccountsRecord> KEY_PARTYACCOUNTS_PRIMARY = UniqueKeys0.KEY_PARTYACCOUNTS_PRIMARY;
	public static final UniqueKey<PartyaccountsRecord> KEY_PARTYACCOUNTS_ID_UNIQUE = UniqueKeys0.KEY_PARTYACCOUNTS_ID_UNIQUE;
	public static final UniqueKey<ProviderfilerelationshipsRecord> KEY_PROVIDERFILERELATIONSHIPS_PRIMARY = UniqueKeys0.KEY_PROVIDERFILERELATIONSHIPS_PRIMARY;
	public static final UniqueKey<ProviderfilerelationshipsRecord> KEY_PROVIDERFILERELATIONSHIPS_ID_UNIQUE = UniqueKeys0.KEY_PROVIDERFILERELATIONSHIPS_ID_UNIQUE;
	public static final UniqueKey<ProviderfilesRecord> KEY_PROVIDERFILES_PRIMARY = UniqueKeys0.KEY_PROVIDERFILES_PRIMARY;
	public static final UniqueKey<ProviderfilesRecord> KEY_PROVIDERFILES_ID_UNIQUE = UniqueKeys0.KEY_PROVIDERFILES_ID_UNIQUE;
	public static final UniqueKey<ProviderfilesRecord> KEY_PROVIDERFILES_UUID_UNIQUE = UniqueKeys0.KEY_PROVIDERFILES_UUID_UNIQUE;
	public static final UniqueKey<ProvidersRecord> KEY_PROVIDERS_PRIMARY = UniqueKeys0.KEY_PROVIDERS_PRIMARY;
	public static final UniqueKey<ProvidersRecord> KEY_PROVIDERS_ID_UNIQUE = UniqueKeys0.KEY_PROVIDERS_ID_UNIQUE;
	public static final UniqueKey<ProvidersRecord> KEY_PROVIDERS_UUID_UNIQUE = UniqueKeys0.KEY_PROVIDERS_UUID_UNIQUE;
	public static final UniqueKey<ProvidersoldRecord> KEY_PROVIDERSOLD_PRIMARY = UniqueKeys0.KEY_PROVIDERSOLD_PRIMARY;
	public static final UniqueKey<ProvidersoldRecord> KEY_PROVIDERSOLD_ID_UNIQUE = UniqueKeys0.KEY_PROVIDERSOLD_ID_UNIQUE;
	public static final UniqueKey<ProvidersoldRecord> KEY_PROVIDERSOLD_UUID_UNIQUE = UniqueKeys0.KEY_PROVIDERSOLD_UUID_UNIQUE;
	public static final UniqueKey<ServersRecord> KEY_SERVERS_PRIMARY = UniqueKeys0.KEY_SERVERS_PRIMARY;
	public static final UniqueKey<ServersRecord> KEY_SERVERS_ID_UNIQUE = UniqueKeys0.KEY_SERVERS_ID_UNIQUE;
	public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = UniqueKeys0.KEY_USERS_PRIMARY;
	public static final UniqueKey<UsersRecord> KEY_USERS_ID_UNIQUE = UniqueKeys0.KEY_USERS_ID_UNIQUE;
	public static final UniqueKey<UsersRecord> KEY_USERS_NAME_UNIQUE = UniqueKeys0.KEY_USERS_NAME_UNIQUE;
	public static final UniqueKey<VirtualproviderprovidersRecord> KEY_VIRTUALPROVIDERPROVIDERS_PRIMARY = UniqueKeys0.KEY_VIRTUALPROVIDERPROVIDERS_PRIMARY;
	public static final UniqueKey<VirtualproviderprovidersRecord> KEY_VIRTUALPROVIDERPROVIDERS_ID_UNIQUE = UniqueKeys0.KEY_VIRTUALPROVIDERPROVIDERS_ID_UNIQUE;
	public static final UniqueKey<VirtualprovidersRecord> KEY_VIRTUALPROVIDERS_PRIMARY = UniqueKeys0.KEY_VIRTUALPROVIDERS_PRIMARY;
	public static final UniqueKey<VirtualprovidersRecord> KEY_VIRTUALPROVIDERS_ID_UNIQUE = UniqueKeys0.KEY_VIRTUALPROVIDERS_ID_UNIQUE;
	public static final UniqueKey<VirtualprovidersRecord> KEY_VIRTUALPROVIDERS_UUID_UNIQUE = UniqueKeys0.KEY_VIRTUALPROVIDERS_UUID_UNIQUE;
	public static final UniqueKey<VirtualprovidersRecord> KEY_VIRTUALPROVIDERS_NAME_UNIQUE = UniqueKeys0.KEY_VIRTUALPROVIDERS_NAME_UNIQUE;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------


	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends AbstractKeys {
		public static Identity<DevicesRecord, Integer> IDENTITY_DEVICES = createIdentity(Devices.DEVICES, Devices.DEVICES.ID);
		public static Identity<DistributordestinationsRecord, Integer> IDENTITY_DISTRIBUTORDESTINATIONS = createIdentity(Distributordestinations.DISTRIBUTORDESTINATIONS, Distributordestinations.DISTRIBUTORDESTINATIONS.ID);
		public static Identity<DistributordirectoriesRecord, Integer> IDENTITY_DISTRIBUTORDIRECTORIES = createIdentity(Distributordirectories.DISTRIBUTORDIRECTORIES, Distributordirectories.DISTRIBUTORDIRECTORIES.ID);
		public static Identity<DistributorqueueRecord, Integer> IDENTITY_DISTRIBUTORQUEUE = createIdentity(Distributorqueue.DISTRIBUTORQUEUE, Distributorqueue.DISTRIBUTORQUEUE.ID);
		public static Identity<HomesRecord, Integer> IDENTITY_HOMES = createIdentity(Homes.HOMES, Homes.HOMES.ID);
		public static Identity<MediachaptersRecord, Integer> IDENTITY_MEDIACHAPTERS = createIdentity(Mediachapters.MEDIACHAPTERS, Mediachapters.MEDIACHAPTERS.ID);
		public static Identity<MediafilesRecord, Integer> IDENTITY_MEDIAFILES = createIdentity(Mediafiles.MEDIAFILES, Mediafiles.MEDIAFILES.ID);
		public static Identity<MediastreamsRecord, Integer> IDENTITY_MEDIASTREAMS = createIdentity(Mediastreams.MEDIASTREAMS, Mediastreams.MEDIASTREAMS.ID);
		public static Identity<ProviderfilerelationshipsRecord, Integer> IDENTITY_PROVIDERFILERELATIONSHIPS = createIdentity(Providerfilerelationships.PROVIDERFILERELATIONSHIPS, Providerfilerelationships.PROVIDERFILERELATIONSHIPS.ID);
		public static Identity<ProviderfilesRecord, Integer> IDENTITY_PROVIDERFILES = createIdentity(Providerfiles.PROVIDERFILES, Providerfiles.PROVIDERFILES.ID);
		public static Identity<ProvidersRecord, Integer> IDENTITY_PROVIDERS = createIdentity(Providers.PROVIDERS, Providers.PROVIDERS.ID);
		public static Identity<ProvidersoldRecord, Integer> IDENTITY_PROVIDERSOLD = createIdentity(Providersold.PROVIDERSOLD, Providersold.PROVIDERSOLD.ID);
		public static Identity<ServersRecord, Integer> IDENTITY_SERVERS = createIdentity(Servers.SERVERS, Servers.SERVERS.ID);
		public static Identity<VirtualproviderprovidersRecord, Integer> IDENTITY_VIRTUALPROVIDERPROVIDERS = createIdentity(Virtualproviderproviders.VIRTUALPROVIDERPROVIDERS, Virtualproviderproviders.VIRTUALPROVIDERPROVIDERS.ID);
		public static Identity<VirtualprovidersRecord, Integer> IDENTITY_VIRTUALPROVIDERS = createIdentity(Virtualproviders.VIRTUALPROVIDERS, Virtualproviders.VIRTUALPROVIDERS.ID);
	}

	private static class UniqueKeys0 extends AbstractKeys {
		public static final UniqueKey<AuthenticationRecord> KEY_AUTHENTICATION_PRIMARY = createUniqueKey(Authentication.AUTHENTICATION, "KEY_Authentication_PRIMARY", Authentication.AUTHENTICATION.ID);
		public static final UniqueKey<AuthenticationRecord> KEY_AUTHENTICATION_ID_UNIQUE = createUniqueKey(Authentication.AUTHENTICATION, "KEY_Authentication_id_UNIQUE", Authentication.AUTHENTICATION.ID);
		public static final UniqueKey<DevicesRecord> KEY_DEVICES_PRIMARY = createUniqueKey(Devices.DEVICES, "KEY_devices_PRIMARY", Devices.DEVICES.ID);
		public static final UniqueKey<DevicesRecord> KEY_DEVICES_ID_UNIQUE = createUniqueKey(Devices.DEVICES, "KEY_devices_id_UNIQUE", Devices.DEVICES.ID);
		public static final UniqueKey<DistributordestinationsRecord> KEY_DISTRIBUTORDESTINATIONS_PRIMARY = createUniqueKey(Distributordestinations.DISTRIBUTORDESTINATIONS, "KEY_distributorDestinations_PRIMARY", Distributordestinations.DISTRIBUTORDESTINATIONS.ID);
		public static final UniqueKey<DistributordestinationsRecord> KEY_DISTRIBUTORDESTINATIONS_ID_UNIQUE = createUniqueKey(Distributordestinations.DISTRIBUTORDESTINATIONS, "KEY_distributorDestinations_id_UNIQUE", Distributordestinations.DISTRIBUTORDESTINATIONS.ID);
		public static final UniqueKey<DistributordirectoriesRecord> KEY_DISTRIBUTORDIRECTORIES_PRIMARY = createUniqueKey(Distributordirectories.DISTRIBUTORDIRECTORIES, "KEY_distributorDirectories_PRIMARY", Distributordirectories.DISTRIBUTORDIRECTORIES.ID);
		public static final UniqueKey<DistributordirectoriesRecord> KEY_DISTRIBUTORDIRECTORIES_ID_UNIQUE = createUniqueKey(Distributordirectories.DISTRIBUTORDIRECTORIES, "KEY_distributorDirectories_id_UNIQUE", Distributordirectories.DISTRIBUTORDIRECTORIES.ID);
		public static final UniqueKey<DistributorqueueRecord> KEY_DISTRIBUTORQUEUE_PRIMARY = createUniqueKey(Distributorqueue.DISTRIBUTORQUEUE, "KEY_distributorQueue_PRIMARY", Distributorqueue.DISTRIBUTORQUEUE.ID);
		public static final UniqueKey<DistributorqueueRecord> KEY_DISTRIBUTORQUEUE_ID_UNIQUE = createUniqueKey(Distributorqueue.DISTRIBUTORQUEUE, "KEY_distributorQueue_id_UNIQUE", Distributorqueue.DISTRIBUTORQUEUE.ID);
		public static final UniqueKey<HomeaccountsRecord> KEY_HOMEACCOUNTS_PRIMARY = createUniqueKey(Homeaccounts.HOMEACCOUNTS, "KEY_HomeAccounts_PRIMARY", Homeaccounts.HOMEACCOUNTS.ID);
		public static final UniqueKey<HomeaccountsRecord> KEY_HOMEACCOUNTS_ID_UNIQUE = createUniqueKey(Homeaccounts.HOMEACCOUNTS, "KEY_HomeAccounts_id_UNIQUE", Homeaccounts.HOMEACCOUNTS.ID);
		public static final UniqueKey<HomesRecord> KEY_HOMES_PRIMARY = createUniqueKey(Homes.HOMES, "KEY_Homes_PRIMARY", Homes.HOMES.ID);
		public static final UniqueKey<HomesRecord> KEY_HOMES_ID_UNIQUE = createUniqueKey(Homes.HOMES, "KEY_Homes_id_UNIQUE", Homes.HOMES.ID);
		public static final UniqueKey<MediachaptersRecord> KEY_MEDIACHAPTERS_PRIMARY = createUniqueKey(Mediachapters.MEDIACHAPTERS, "KEY_MediaChapters_PRIMARY", Mediachapters.MEDIACHAPTERS.ID);
		public static final UniqueKey<MediachaptersRecord> KEY_MEDIACHAPTERS_ID_UNIQUE = createUniqueKey(Mediachapters.MEDIACHAPTERS, "KEY_MediaChapters_Id_UNIQUE", Mediachapters.MEDIACHAPTERS.ID);
		public static final UniqueKey<MediachaptersRecord> KEY_MEDIACHAPTERS_UUID_UNIQUE = createUniqueKey(Mediachapters.MEDIACHAPTERS, "KEY_MediaChapters_Uuid_UNIQUE", Mediachapters.MEDIACHAPTERS.UUID);
		public static final UniqueKey<MediafilesRecord> KEY_MEDIAFILES_PRIMARY = createUniqueKey(Mediafiles.MEDIAFILES, "KEY_MediaFiles_PRIMARY", Mediafiles.MEDIAFILES.ID);
		public static final UniqueKey<MediafilesRecord> KEY_MEDIAFILES_ID_UNIQUE = createUniqueKey(Mediafiles.MEDIAFILES, "KEY_MediaFiles_Id_UNIQUE", Mediafiles.MEDIAFILES.ID);
		public static final UniqueKey<MediafilesRecord> KEY_MEDIAFILES_UUID_UNIQUE = createUniqueKey(Mediafiles.MEDIAFILES, "KEY_MediaFiles_Uuid_UNIQUE", Mediafiles.MEDIAFILES.UUID);
		public static final UniqueKey<MediastreamsRecord> KEY_MEDIASTREAMS_PRIMARY = createUniqueKey(Mediastreams.MEDIASTREAMS, "KEY_MediaStreams_PRIMARY", Mediastreams.MEDIASTREAMS.ID);
		public static final UniqueKey<MediastreamsRecord> KEY_MEDIASTREAMS_ID_UNIQUE = createUniqueKey(Mediastreams.MEDIASTREAMS, "KEY_MediaStreams_Id_UNIQUE", Mediastreams.MEDIASTREAMS.ID);
		public static final UniqueKey<MediastreamsRecord> KEY_MEDIASTREAMS_UUID_UNIQUE = createUniqueKey(Mediastreams.MEDIASTREAMS, "KEY_MediaStreams_Uuid_UNIQUE", Mediastreams.MEDIASTREAMS.UUID);
		public static final UniqueKey<PartiesRecord> KEY_PARTIES_PRIMARY = createUniqueKey(Parties.PARTIES, "KEY_Parties_PRIMARY", Parties.PARTIES.ID);
		public static final UniqueKey<PartiesRecord> KEY_PARTIES_ID_UNIQUE = createUniqueKey(Parties.PARTIES, "KEY_Parties_id_UNIQUE", Parties.PARTIES.ID);
		public static final UniqueKey<PartyaccountsRecord> KEY_PARTYACCOUNTS_PRIMARY = createUniqueKey(Partyaccounts.PARTYACCOUNTS, "KEY_PartyAccounts_PRIMARY", Partyaccounts.PARTYACCOUNTS.ID);
		public static final UniqueKey<PartyaccountsRecord> KEY_PARTYACCOUNTS_ID_UNIQUE = createUniqueKey(Partyaccounts.PARTYACCOUNTS, "KEY_PartyAccounts_id_UNIQUE", Partyaccounts.PARTYACCOUNTS.ID);
		public static final UniqueKey<ProviderfilerelationshipsRecord> KEY_PROVIDERFILERELATIONSHIPS_PRIMARY = createUniqueKey(Providerfilerelationships.PROVIDERFILERELATIONSHIPS, "KEY_ProviderFileRelationships_PRIMARY", Providerfilerelationships.PROVIDERFILERELATIONSHIPS.ID);
		public static final UniqueKey<ProviderfilerelationshipsRecord> KEY_PROVIDERFILERELATIONSHIPS_ID_UNIQUE = createUniqueKey(Providerfilerelationships.PROVIDERFILERELATIONSHIPS, "KEY_ProviderFileRelationships_Id_UNIQUE", Providerfilerelationships.PROVIDERFILERELATIONSHIPS.ID);
		public static final UniqueKey<ProviderfilesRecord> KEY_PROVIDERFILES_PRIMARY = createUniqueKey(Providerfiles.PROVIDERFILES, "KEY_ProviderFiles_PRIMARY", Providerfiles.PROVIDERFILES.ID);
		public static final UniqueKey<ProviderfilesRecord> KEY_PROVIDERFILES_ID_UNIQUE = createUniqueKey(Providerfiles.PROVIDERFILES, "KEY_ProviderFiles_id_UNIQUE", Providerfiles.PROVIDERFILES.ID);
		public static final UniqueKey<ProviderfilesRecord> KEY_PROVIDERFILES_UUID_UNIQUE = createUniqueKey(Providerfiles.PROVIDERFILES, "KEY_ProviderFiles_Uuid_UNIQUE", Providerfiles.PROVIDERFILES.UUID);
		public static final UniqueKey<ProvidersRecord> KEY_PROVIDERS_PRIMARY = createUniqueKey(Providers.PROVIDERS, "KEY_Providers_PRIMARY", Providers.PROVIDERS.ID);
		public static final UniqueKey<ProvidersRecord> KEY_PROVIDERS_ID_UNIQUE = createUniqueKey(Providers.PROVIDERS, "KEY_Providers_Id_UNIQUE", Providers.PROVIDERS.ID);
		public static final UniqueKey<ProvidersRecord> KEY_PROVIDERS_UUID_UNIQUE = createUniqueKey(Providers.PROVIDERS, "KEY_Providers_Uuid_UNIQUE", Providers.PROVIDERS.UUID);
		public static final UniqueKey<ProvidersoldRecord> KEY_PROVIDERSOLD_PRIMARY = createUniqueKey(Providersold.PROVIDERSOLD, "KEY_providersold_PRIMARY", Providersold.PROVIDERSOLD.ID);
		public static final UniqueKey<ProvidersoldRecord> KEY_PROVIDERSOLD_ID_UNIQUE = createUniqueKey(Providersold.PROVIDERSOLD, "KEY_providersold_id_UNIQUE", Providersold.PROVIDERSOLD.ID);
		public static final UniqueKey<ProvidersoldRecord> KEY_PROVIDERSOLD_UUID_UNIQUE = createUniqueKey(Providersold.PROVIDERSOLD, "KEY_providersold_uuid_UNIQUE", Providersold.PROVIDERSOLD.UUID);
		public static final UniqueKey<ServersRecord> KEY_SERVERS_PRIMARY = createUniqueKey(Servers.SERVERS, "KEY_servers_PRIMARY", Servers.SERVERS.ID);
		public static final UniqueKey<ServersRecord> KEY_SERVERS_ID_UNIQUE = createUniqueKey(Servers.SERVERS, "KEY_servers_id_UNIQUE", Servers.SERVERS.ID);
		public static final UniqueKey<UsersRecord> KEY_USERS_PRIMARY = createUniqueKey(Users.USERS, "KEY_Users_PRIMARY", Users.USERS.ID);
		public static final UniqueKey<UsersRecord> KEY_USERS_ID_UNIQUE = createUniqueKey(Users.USERS, "KEY_Users_id_UNIQUE", Users.USERS.ID);
		public static final UniqueKey<UsersRecord> KEY_USERS_NAME_UNIQUE = createUniqueKey(Users.USERS, "KEY_Users_name_UNIQUE", Users.USERS.NAME);
		public static final UniqueKey<VirtualproviderprovidersRecord> KEY_VIRTUALPROVIDERPROVIDERS_PRIMARY = createUniqueKey(Virtualproviderproviders.VIRTUALPROVIDERPROVIDERS, "KEY_VirtualProviderProviders_PRIMARY", Virtualproviderproviders.VIRTUALPROVIDERPROVIDERS.ID);
		public static final UniqueKey<VirtualproviderprovidersRecord> KEY_VIRTUALPROVIDERPROVIDERS_ID_UNIQUE = createUniqueKey(Virtualproviderproviders.VIRTUALPROVIDERPROVIDERS, "KEY_VirtualProviderProviders_id_UNIQUE", Virtualproviderproviders.VIRTUALPROVIDERPROVIDERS.ID);
		public static final UniqueKey<VirtualprovidersRecord> KEY_VIRTUALPROVIDERS_PRIMARY = createUniqueKey(Virtualproviders.VIRTUALPROVIDERS, "KEY_VirtualProviders_PRIMARY", Virtualproviders.VIRTUALPROVIDERS.ID);
		public static final UniqueKey<VirtualprovidersRecord> KEY_VIRTUALPROVIDERS_ID_UNIQUE = createUniqueKey(Virtualproviders.VIRTUALPROVIDERS, "KEY_VirtualProviders_id_UNIQUE", Virtualproviders.VIRTUALPROVIDERS.ID);
		public static final UniqueKey<VirtualprovidersRecord> KEY_VIRTUALPROVIDERS_UUID_UNIQUE = createUniqueKey(Virtualproviders.VIRTUALPROVIDERS, "KEY_VirtualProviders_uuid_UNIQUE", Virtualproviders.VIRTUALPROVIDERS.UUID);
		public static final UniqueKey<VirtualprovidersRecord> KEY_VIRTUALPROVIDERS_NAME_UNIQUE = createUniqueKey(Virtualproviders.VIRTUALPROVIDERS, "KEY_VirtualProviders_name_UNIQUE", Virtualproviders.VIRTUALPROVIDERS.NAME);
	}
}
