/*
 * This file is generated by jOOQ.
 */
package com.atherapp.common.database.jooq;


import com.atherapp.common.database.jooq.tables.*;
import com.atherapp.common.database.jooq.tables.*;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in thehoard
 */
@Generated(value = {"http://www.jooq.org", "jOOQ version:3.10.1"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Tables {

	/**
	 * The table <code>thehoard.Authentication</code>.
	 */
	public static final Authentication AUTHENTICATION = com.atherapp.common.database.jooq.tables.Authentication.AUTHENTICATION;

	/**
	 * The table <code>thehoard.devices</code>.
	 */
	public static final Devices DEVICES = com.atherapp.common.database.jooq.tables.Devices.DEVICES;

	/**
	 * The table <code>thehoard.distributorDestinations</code>.
	 */
	public static final Distributordestinations DISTRIBUTORDESTINATIONS = com.atherapp.common.database.jooq.tables.Distributordestinations.DISTRIBUTORDESTINATIONS;

	/**
	 * This table stores all the directories for each destination, to prevent constant API hits to parse destinations.
	 * This is structured differently than the regular files/directories tables because it doesn't use foreign keys.
	 */
	public static final Distributordirectories DISTRIBUTORDIRECTORIES = com.atherapp.common.database.jooq.tables.Distributordirectories.DISTRIBUTORDIRECTORIES;

	/**
	 * The table <code>thehoard.distributorQueue</code>.
	 */
	public static final Distributorqueue DISTRIBUTORQUEUE = com.atherapp.common.database.jooq.tables.Distributorqueue.DISTRIBUTORQUEUE;

	/**
	 * The table <code>thehoard.HomeAccounts</code>.
	 */
	public static final Homeaccounts HOMEACCOUNTS = com.atherapp.common.database.jooq.tables.Homeaccounts.HOMEACCOUNTS;

	/**
	 * The table <code>thehoard.Homes</code>.
	 */
	public static final Homes HOMES = com.atherapp.common.database.jooq.tables.Homes.HOMES;

	/**
	 * The table <code>thehoard.MediaChapters</code>.
	 */
	public static final Mediachapters MEDIACHAPTERS = com.atherapp.common.database.jooq.tables.Mediachapters.MEDIACHAPTERS;

	/**
	 * The table <code>thehoard.MediaFiles</code>.
	 */
	public static final Mediafiles MEDIAFILES = com.atherapp.common.database.jooq.tables.Mediafiles.MEDIAFILES;

	/**
	 * The table <code>thehoard.MediaStreams</code>.
	 */
	public static final Mediastreams MEDIASTREAMS = com.atherapp.common.database.jooq.tables.Mediastreams.MEDIASTREAMS;

	/**
	 * The table <code>thehoard.Parties</code>.
	 */
	public static final Parties PARTIES = com.atherapp.common.database.jooq.tables.Parties.PARTIES;

	/**
	 * The table <code>thehoard.PartyAccounts</code>.
	 */
	public static final Partyaccounts PARTYACCOUNTS = com.atherapp.common.database.jooq.tables.Partyaccounts.PARTYACCOUNTS;

	/**
	 * The table <code>thehoard.ProviderFileRelationships</code>.
	 */
	public static final Providerfilerelationships PROVIDERFILERELATIONSHIPS = com.atherapp.common.database.jooq.tables.Providerfilerelationships.PROVIDERFILERELATIONSHIPS;

	/**
	 * The table <code>thehoard.ProviderFiles</code>.
	 */
	public static final Providerfiles PROVIDERFILES = com.atherapp.common.database.jooq.tables.Providerfiles.PROVIDERFILES;

	/**
	 * The table <code>thehoard.Providers</code>.
	 */
	public static final Providers PROVIDERS = com.atherapp.common.database.jooq.tables.Providers.PROVIDERS;

	/**
	 * The table <code>thehoard.providersold</code>.
	 */
	public static final Providersold PROVIDERSOLD = com.atherapp.common.database.jooq.tables.Providersold.PROVIDERSOLD;

	/**
	 * The table <code>thehoard.servers</code>.
	 */
	public static final Servers SERVERS = com.atherapp.common.database.jooq.tables.Servers.SERVERS;

	/**
	 * The table <code>thehoard.Users</code>.
	 */
	public static final Users USERS = com.atherapp.common.database.jooq.tables.Users.USERS;

	/**
	 * Provider references for virtual providers
	 */
	public static final Virtualproviderproviders VIRTUALPROVIDERPROVIDERS = com.atherapp.common.database.jooq.tables.Virtualproviderproviders.VIRTUALPROVIDERPROVIDERS;

	/**
	 * Virtual provider structures used for spanning across multiple providers
	 */
	public static final Virtualproviders VIRTUALPROVIDERS = com.atherapp.common.database.jooq.tables.Virtualproviders.VIRTUALPROVIDERS;
}
