/*
 * This file is generated by jOOQ.
 */
package com.atherapp.common.database.jooq;


import com.atherapp.common.database.jooq.tables.*;
import com.atherapp.common.database.jooq.tables.*;
import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;

import javax.annotation.Generated;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {"http://www.jooq.org", "jOOQ version:3.10.1"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class Thehoard extends SchemaImpl {

	/**
	 * The reference instance of <code>thehoard</code>
	 */
	public static final Thehoard THEHOARD = new Thehoard();
	private static final long serialVersionUID = -1648835039;
	/**
	 * The table <code>thehoard.Authentication</code>.
	 */
	public final Authentication AUTHENTICATION = com.atherapp.common.database.jooq.tables.Authentication.AUTHENTICATION;

	/**
	 * The table <code>thehoard.devices</code>.
	 */
	public final Devices DEVICES = com.atherapp.common.database.jooq.tables.Devices.DEVICES;

	/**
	 * The table <code>thehoard.distributorDestinations</code>.
	 */
	public final Distributordestinations DISTRIBUTORDESTINATIONS = com.atherapp.common.database.jooq.tables.Distributordestinations.DISTRIBUTORDESTINATIONS;

	/**
	 * This table stores all the directories for each destination, to prevent constant API hits to parse destinations.
	 * This is structured differently than the regular files/directories tables because it doesn't use foreign keys.
	 */
	public final Distributordirectories DISTRIBUTORDIRECTORIES = com.atherapp.common.database.jooq.tables.Distributordirectories.DISTRIBUTORDIRECTORIES;

	/**
	 * The table <code>thehoard.distributorQueue</code>.
	 */
	public final Distributorqueue DISTRIBUTORQUEUE = com.atherapp.common.database.jooq.tables.Distributorqueue.DISTRIBUTORQUEUE;

	/**
	 * The table <code>thehoard.HomeAccounts</code>.
	 */
	public final Homeaccounts HOMEACCOUNTS = com.atherapp.common.database.jooq.tables.Homeaccounts.HOMEACCOUNTS;

	/**
	 * The table <code>thehoard.Homes</code>.
	 */
	public final Homes HOMES = com.atherapp.common.database.jooq.tables.Homes.HOMES;

	/**
	 * The table <code>thehoard.MediaChapters</code>.
	 */
	public final Mediachapters MEDIACHAPTERS = com.atherapp.common.database.jooq.tables.Mediachapters.MEDIACHAPTERS;

	/**
	 * The table <code>thehoard.MediaFiles</code>.
	 */
	public final Mediafiles MEDIAFILES = com.atherapp.common.database.jooq.tables.Mediafiles.MEDIAFILES;

	/**
	 * The table <code>thehoard.MediaStreams</code>.
	 */
	public final Mediastreams MEDIASTREAMS = com.atherapp.common.database.jooq.tables.Mediastreams.MEDIASTREAMS;

	/**
	 * The table <code>thehoard.Parties</code>.
	 */
	public final Parties PARTIES = com.atherapp.common.database.jooq.tables.Parties.PARTIES;

	/**
	 * The table <code>thehoard.PartyAccounts</code>.
	 */
	public final Partyaccounts PARTYACCOUNTS = com.atherapp.common.database.jooq.tables.Partyaccounts.PARTYACCOUNTS;

	/**
	 * The table <code>thehoard.ProviderFileRelationships</code>.
	 */
	public final Providerfilerelationships PROVIDERFILERELATIONSHIPS = com.atherapp.common.database.jooq.tables.Providerfilerelationships.PROVIDERFILERELATIONSHIPS;

	/**
	 * The table <code>thehoard.ProviderFiles</code>.
	 */
	public final Providerfiles PROVIDERFILES = com.atherapp.common.database.jooq.tables.Providerfiles.PROVIDERFILES;

	/**
	 * The table <code>thehoard.Providers</code>.
	 */
	public final Providers PROVIDERS = com.atherapp.common.database.jooq.tables.Providers.PROVIDERS;

	/**
	 * The table <code>thehoard.providersold</code>.
	 */
	public final Providersold PROVIDERSOLD = com.atherapp.common.database.jooq.tables.Providersold.PROVIDERSOLD;

	/**
	 * The table <code>thehoard.servers</code>.
	 */
	public final Servers SERVERS = com.atherapp.common.database.jooq.tables.Servers.SERVERS;

	/**
	 * The table <code>thehoard.Users</code>.
	 */
	public final Users USERS = com.atherapp.common.database.jooq.tables.Users.USERS;

	/**
	 * Provider references for virtual providers
	 */
	public final Virtualproviderproviders VIRTUALPROVIDERPROVIDERS = com.atherapp.common.database.jooq.tables.Virtualproviderproviders.VIRTUALPROVIDERPROVIDERS;

	/**
	 * Virtual provider structures used for spanning across multiple providers
	 */
	public final Virtualproviders VIRTUALPROVIDERS = com.atherapp.common.database.jooq.tables.Virtualproviders.VIRTUALPROVIDERS;

	/**
	 * No further instances allowed
	 */
	private Thehoard() {
		super("thehoard", null);
	}


	/**
	 * {@inheritDoc}
	 */
	@Override
	public Catalog getCatalog() {
		return DefaultCatalog.DEFAULT_CATALOG;
	}

	@Override
	public final List<Table<?>> getTables() {
		List result = new ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final List<Table<?>> getTables0() {
		return Arrays.<Table<?>>asList(Authentication.AUTHENTICATION, Devices.DEVICES, Distributordestinations.DISTRIBUTORDESTINATIONS, Distributordirectories.DISTRIBUTORDIRECTORIES, Distributorqueue.DISTRIBUTORQUEUE, Homeaccounts.HOMEACCOUNTS, Homes.HOMES, Mediachapters.MEDIACHAPTERS, Mediafiles.MEDIAFILES, Mediastreams.MEDIASTREAMS, Parties.PARTIES, Partyaccounts.PARTYACCOUNTS, Providerfilerelationships.PROVIDERFILERELATIONSHIPS, Providerfiles.PROVIDERFILES, Providers.PROVIDERS, Providersold.PROVIDERSOLD, Servers.SERVERS, Users.USERS, Virtualproviderproviders.VIRTUALPROVIDERPROVIDERS, Virtualproviders.VIRTUALPROVIDERS);
	}
}
