/*
 * This file is generated by jOOQ.
*/
package media.thehoard.common.database.jooq.routines;


import javax.annotation.Generated;

import media.thehoard.hoardmediaserver.common.database.jooq.Thehoard;

import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Revokeauthentication extends AbstractRoutine<Integer> {

    private static final long serialVersionUID = -445814114;

    /**
     * The parameter <code>thehoard.revokeAuthentication.RETURN_VALUE</code>.
     */
    public static final Parameter<Integer> RETURN_VALUE = createParameter("RETURN_VALUE", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>thehoard.revokeAuthentication.authId</code>.
     */
    public static final Parameter<Integer> AUTHID = createParameter("authId", org.jooq.impl.SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public Revokeauthentication() {
        super("revokeAuthentication", Thehoard.THEHOARD, org.jooq.impl.SQLDataType.INTEGER);

        setReturnParameter(RETURN_VALUE);
        addInParameter(AUTHID);
    }

    /**
     * Set the <code>authId</code> parameter IN value to the routine
     */
    public void setAuthid(Integer value) {
        setValue(AUTHID, value);
    }

    /**
     * Set the <code>authId</code> parameter to the function to be used with a {@link org.jooq.Select} statement
     */
    public void setAuthid(Field<Integer> field) {
        setField(AUTHID, field);
    }
}
