/*
 * This file is generated by jOOQ.
*/
package media.thehoard.common.database.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import media.thehoard.common.database.jooq.Indexes;
import media.thehoard.common.database.jooq.Keys;
import media.thehoard.common.database.jooq.Thehoard;
import media.thehoard.common.database.jooq.tables.records.DevicesRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Devices extends TableImpl<DevicesRecord> {

    private static final long serialVersionUID = 408420364;

    /**
     * The reference instance of <code>thehoard.devices</code>
     */
    public static final Devices DEVICES = new Devices();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DevicesRecord> getRecordType() {
        return DevicesRecord.class;
    }

    /**
     * The column <code>thehoard.devices.id</code>.
     */
    public final TableField<DevicesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>thehoard.devices.uuid</code>.
     */
    public final TableField<DevicesRecord, String> UUID = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>thehoard.devices.name</code>.
     */
    public final TableField<DevicesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>thehoard.devices.dateCreated</code>.
     */
    public final TableField<DevicesRecord, Timestamp> DATECREATED = createField("dateCreated", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>thehoard.devices.dateUpdated</code>.
     */
    public final TableField<DevicesRecord, Timestamp> DATEUPDATED = createField("dateUpdated", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>thehoard.devices</code> table reference
     */
    public Devices() {
        this(DSL.name("devices"), null);
    }

    /**
     * Create an aliased <code>thehoard.devices</code> table reference
     */
    public Devices(String alias) {
        this(DSL.name(alias), DEVICES);
    }

    /**
     * Create an aliased <code>thehoard.devices</code> table reference
     */
    public Devices(Name alias) {
        this(alias, DEVICES);
    }

    private Devices(Name alias, Table<DevicesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Devices(Name alias, Table<DevicesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Thehoard.THEHOARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.DEVICES_ID_UNIQUE, Indexes.DEVICES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<DevicesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_DEVICES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<DevicesRecord> getPrimaryKey() {
        return Keys.KEY_DEVICES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<DevicesRecord>> getKeys() {
        return Arrays.<UniqueKey<DevicesRecord>>asList(Keys.KEY_DEVICES_PRIMARY, Keys.KEY_DEVICES_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Devices as(String alias) {
        return new Devices(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Devices as(Name alias) {
        return new Devices(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Devices rename(String name) {
        return new Devices(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Devices rename(Name name) {
        return new Devices(name, null);
    }
}
