/*
 * This file is generated by jOOQ.
*/
package media.thehoard.common.database.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import media.thehoard.common.database.jooq.Indexes;
import media.thehoard.common.database.jooq.Keys;
import media.thehoard.common.database.jooq.Thehoard;
import media.thehoard.common.database.jooq.tables.records.HomeaccountsRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Homeaccounts extends TableImpl<HomeaccountsRecord> {

    private static final long serialVersionUID = -121276827;

    /**
     * The reference instance of <code>thehoard.HomeAccounts</code>
     */
    public static final Homeaccounts HOMEACCOUNTS = new Homeaccounts();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<HomeaccountsRecord> getRecordType() {
        return HomeaccountsRecord.class;
    }

    /**
     * The column <code>thehoard.HomeAccounts.id</code>.
     */
    public final TableField<HomeaccountsRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>thehoard.HomeAccounts.accountId</code>.
     */
    public final TableField<HomeaccountsRecord, Integer> ACCOUNTID = createField("accountId", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>thehoard.HomeAccounts.homeId</code>.
     */
    public final TableField<HomeaccountsRecord, Integer> HOMEID = createField("homeId", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>thehoard.HomeAccounts.pin</code>.
     */
    public final TableField<HomeaccountsRecord, Integer> PIN = createField("pin", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>thehoard.HomeAccounts.dateJoined</code>.
     */
    public final TableField<HomeaccountsRecord, Timestamp> DATEJOINED = createField("dateJoined", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>thehoard.HomeAccounts.dateLeft</code>.
     */
    public final TableField<HomeaccountsRecord, Timestamp> DATELEFT = createField("dateLeft", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>thehoard.HomeAccounts</code> table reference
     */
    public Homeaccounts() {
        this(DSL.name("HomeAccounts"), null);
    }

    /**
     * Create an aliased <code>thehoard.HomeAccounts</code> table reference
     */
    public Homeaccounts(String alias) {
        this(DSL.name(alias), HOMEACCOUNTS);
    }

    /**
     * Create an aliased <code>thehoard.HomeAccounts</code> table reference
     */
    public Homeaccounts(Name alias) {
        this(alias, HOMEACCOUNTS);
    }

    private Homeaccounts(Name alias, Table<HomeaccountsRecord> aliased) {
        this(alias, aliased, null);
    }

    private Homeaccounts(Name alias, Table<HomeaccountsRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Thehoard.THEHOARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.HOMEACCOUNTS_ID_UNIQUE, Indexes.HOMEACCOUNTS_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<HomeaccountsRecord, Integer> getIdentity() {
        return Keys.IDENTITY_HOMEACCOUNTS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<HomeaccountsRecord> getPrimaryKey() {
        return Keys.KEY_HOMEACCOUNTS_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<HomeaccountsRecord>> getKeys() {
        return Arrays.<UniqueKey<HomeaccountsRecord>>asList(Keys.KEY_HOMEACCOUNTS_PRIMARY, Keys.KEY_HOMEACCOUNTS_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Homeaccounts as(String alias) {
        return new Homeaccounts(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Homeaccounts as(Name alias) {
        return new Homeaccounts(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Homeaccounts rename(String name) {
        return new Homeaccounts(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Homeaccounts rename(Name name) {
        return new Homeaccounts(name, null);
    }
}
