/*
 * This file is generated by jOOQ.
*/
package media.thehoard.common.database.jooq.tables;


import java.sql.Timestamp;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import media.thehoard.common.database.jooq.Indexes;
import media.thehoard.common.database.jooq.Keys;
import media.thehoard.common.database.jooq.Thehoard;
import media.thehoard.common.database.jooq.tables.records.PartiesRecord;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Parties extends TableImpl<PartiesRecord> {

    private static final long serialVersionUID = 1686480064;

    /**
     * The reference instance of <code>thehoard.Parties</code>
     */
    public static final Parties PARTIES = new Parties();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PartiesRecord> getRecordType() {
        return PartiesRecord.class;
    }

    /**
     * The column <code>thehoard.Parties.id</code>.
     */
    public final TableField<PartiesRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>thehoard.Parties.ownerId</code>.
     */
    public final TableField<PartiesRecord, Integer> OWNERID = createField("ownerId", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>thehoard.Parties.name</code>.
     */
    public final TableField<PartiesRecord, String> NAME = createField("name", org.jooq.impl.SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>thehoard.Parties.dateCreated</code>.
     */
    public final TableField<PartiesRecord, Timestamp> DATECREATED = createField("dateCreated", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * The column <code>thehoard.Parties.dateUpdated</code>.
     */
    public final TableField<PartiesRecord, Timestamp> DATEUPDATED = createField("dateUpdated", org.jooq.impl.SQLDataType.TIMESTAMP, this, "");

    /**
     * Create a <code>thehoard.Parties</code> table reference
     */
    public Parties() {
        this(DSL.name("Parties"), null);
    }

    /**
     * Create an aliased <code>thehoard.Parties</code> table reference
     */
    public Parties(String alias) {
        this(DSL.name(alias), PARTIES);
    }

    /**
     * Create an aliased <code>thehoard.Parties</code> table reference
     */
    public Parties(Name alias) {
        this(alias, PARTIES);
    }

    private Parties(Name alias, Table<PartiesRecord> aliased) {
        this(alias, aliased, null);
    }

    private Parties(Name alias, Table<PartiesRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Thehoard.THEHOARD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PARTIES_ID_UNIQUE, Indexes.PARTIES_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<PartiesRecord, Integer> getIdentity() {
        return Keys.IDENTITY_PARTIES;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PartiesRecord> getPrimaryKey() {
        return Keys.KEY_PARTIES_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PartiesRecord>> getKeys() {
        return Arrays.<UniqueKey<PartiesRecord>>asList(Keys.KEY_PARTIES_PRIMARY, Keys.KEY_PARTIES_ID_UNIQUE);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Parties as(String alias) {
        return new Parties(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Parties as(Name alias) {
        return new Parties(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Parties rename(String name) {
        return new Parties(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Parties rename(Name name) {
        return new Parties(name, null);
    }
}
