/*
 * This file is generated by jOOQ.
*/
package com.atherapp.common.database.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import com.atherapp.common.database.jooq.tables.Authentication;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AuthenticationRecord extends UpdatableRecordImpl<AuthenticationRecord> implements Record7<Integer, String, Integer, Integer, Byte, Timestamp, Timestamp> {

    private static final long serialVersionUID = 172451959;

    /**
     * Setter for <code>thehoard.Authentication.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>thehoard.Authentication.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thehoard.Authentication.AccessToken</code>.
     */
    public void setAccesstoken(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>thehoard.Authentication.AccessToken</code>.
     */
    public String getAccesstoken() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thehoard.Authentication.DeviceId</code>.
     */
    public void setDeviceid(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>thehoard.Authentication.DeviceId</code>.
     */
    public Integer getDeviceid() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>thehoard.Authentication.UserId</code>.
     */
    public void setUserid(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>thehoard.Authentication.UserId</code>.
     */
    public Integer getUserid() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>thehoard.Authentication.IsActive</code>.
     */
    public void setIsactive(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>thehoard.Authentication.IsActive</code>.
     */
    public Byte getIsactive() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>thehoard.Authentication.DateCreated</code>.
     */
    public void setDatecreated(Timestamp value) {
        set(5, value);
    }

    /**
     * Getter for <code>thehoard.Authentication.DateCreated</code>.
     */
    public Timestamp getDatecreated() {
        return (Timestamp) get(5);
    }

    /**
     * Setter for <code>thehoard.Authentication.DateRevoked</code>.
     */
    public void setDaterevoked(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>thehoard.Authentication.DateRevoked</code>.
     */
    public Timestamp getDaterevoked() {
        return (Timestamp) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Integer, Byte, Timestamp, Timestamp> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, Integer, Integer, Byte, Timestamp, Timestamp> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Authentication.AUTHENTICATION.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Authentication.AUTHENTICATION.ACCESSTOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return Authentication.AUTHENTICATION.DEVICEID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Authentication.AUTHENTICATION.USERID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return Authentication.AUTHENTICATION.ISACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field6() {
        return Authentication.AUTHENTICATION.DATECREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Authentication.AUTHENTICATION.DATEREVOKED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getAccesstoken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getDeviceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component6() {
        return getDatecreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDaterevoked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getAccesstoken();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getDeviceid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getUserid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value6() {
        return getDatecreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDaterevoked();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationRecord value2(String value) {
        setAccesstoken(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationRecord value3(Integer value) {
        setDeviceid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationRecord value4(Integer value) {
        setUserid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationRecord value5(Byte value) {
        setIsactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationRecord value6(Timestamp value) {
        setDatecreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationRecord value7(Timestamp value) {
        setDaterevoked(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AuthenticationRecord values(Integer value1, String value2, Integer value3, Integer value4, Byte value5, Timestamp value6, Timestamp value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AuthenticationRecord
     */
    public AuthenticationRecord() {
        super(Authentication.AUTHENTICATION);
    }

    /**
     * Create a detached, initialised AuthenticationRecord
     */
    public AuthenticationRecord(Integer id, String accesstoken, Integer deviceid, Integer userid, Byte isactive, Timestamp datecreated, Timestamp daterevoked) {
        super(Authentication.AUTHENTICATION);

        set(0, id);
        set(1, accesstoken);
        set(2, deviceid);
        set(3, userid);
        set(4, isactive);
        set(5, datecreated);
        set(6, daterevoked);
    }
}
