/*
 * This file is generated by jOOQ.
*/
package com.atherapp.common.database.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import com.atherapp.common.database.jooq.tables.Distributorqueue;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DistributorqueueRecord extends UpdatableRecordImpl<DistributorqueueRecord> implements Record7<Integer, String, String, Timestamp, Timestamp, Object, Byte> {

    private static final long serialVersionUID = -300979621;

    /**
     * Setter for <code>thehoard.distributorQueue.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>thehoard.distributorQueue.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thehoard.distributorQueue.fileName</code>.
     */
    public void setFilename(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>thehoard.distributorQueue.fileName</code>.
     */
    public String getFilename() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thehoard.distributorQueue.pathToFile</code>.
     */
    public void setPathtofile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>thehoard.distributorQueue.pathToFile</code>.
     */
    public String getPathtofile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thehoard.distributorQueue.createdAt</code>.
     */
    public void setCreatedat(Timestamp value) {
        set(3, value);
    }

    /**
     * Getter for <code>thehoard.distributorQueue.createdAt</code>.
     */
    public Timestamp getCreatedat() {
        return (Timestamp) get(3);
    }

    /**
     * Setter for <code>thehoard.distributorQueue.completedAt</code>.
     */
    public void setCompletedat(Timestamp value) {
        set(4, value);
    }

    /**
     * Getter for <code>thehoard.distributorQueue.completedAt</code>.
     */
    public Timestamp getCompletedat() {
        return (Timestamp) get(4);
    }

    /**
     * Setter for <code>thehoard.distributorQueue.probeInfo</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public void setProbeinfo(Object value) {
        set(5, value);
    }

    /**
     * Getter for <code>thehoard.distributorQueue.probeInfo</code>.
     */

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    public Object getProbeinfo() {
        return (Object) get(5);
    }

    /**
     * Setter for <code>thehoard.distributorQueue.status</code>.
     */
    public void setStatus(Byte value) {
        set(6, value);
    }

    /**
     * Getter for <code>thehoard.distributorQueue.status</code>.
     */
    public Byte getStatus() {
        return (Byte) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Timestamp, Timestamp, Object, Byte> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, String, String, Timestamp, Timestamp, Object, Byte> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Distributorqueue.DISTRIBUTORQUEUE.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Distributorqueue.DISTRIBUTORQUEUE.FILENAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Distributorqueue.DISTRIBUTORQUEUE.PATHTOFILE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field4() {
        return Distributorqueue.DISTRIBUTORQUEUE.CREATEDAT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field5() {
        return Distributorqueue.DISTRIBUTORQUEUE.COMPLETEDAT;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Field<Object> field6() {
        return Distributorqueue.DISTRIBUTORQUEUE.PROBEINFO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field7() {
        return Distributorqueue.DISTRIBUTORQUEUE.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPathtofile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component4() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component5() {
        return getCompletedat();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object component6() {
        return getProbeinfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getFilename();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPathtofile();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value4() {
        return getCreatedat();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value5() {
        return getCompletedat();
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public Object value6() {
        return getProbeinfo();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value7() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistributorqueueRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistributorqueueRecord value2(String value) {
        setFilename(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistributorqueueRecord value3(String value) {
        setPathtofile(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistributorqueueRecord value4(Timestamp value) {
        setCreatedat(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistributorqueueRecord value5(Timestamp value) {
        setCompletedat(value);
        return this;
    }

    /**
     * @deprecated Unknown data type. Please define an explicit {@link org.jooq.Binding} to specify how this type should be handled.
     */
    @java.lang.Deprecated
    @Override
    public DistributorqueueRecord value6(Object value) {
        setProbeinfo(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistributorqueueRecord value7(Byte value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public DistributorqueueRecord values(Integer value1, String value2, String value3, Timestamp value4, Timestamp value5, Object value6, Byte value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DistributorqueueRecord
     */
    public DistributorqueueRecord() {
        super(Distributorqueue.DISTRIBUTORQUEUE);
    }

    /**
     * Create a detached, initialised DistributorqueueRecord
     */
    public DistributorqueueRecord(Integer id, String filename, String pathtofile, Timestamp createdat, Timestamp completedat, Object probeinfo, Byte status) {
        super(Distributorqueue.DISTRIBUTORQUEUE);

        set(0, id);
        set(1, filename);
        set(2, pathtofile);
        set(3, createdat);
        set(4, completedat);
        set(5, probeinfo);
        set(6, status);
    }
}
