/*
 * This file is generated by jOOQ.
 */
package com.atherapp.common.database.jooq.tables.records;


import com.atherapp.common.database.jooq.tables.Distributordirectories;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This table stores all the directories for each destination, to prevent
 * constant API hits to parse destinations.
 * This is structured differently than the regular files/directories tables
 * because it doesn't use foreign keys.
 */
@Generated(value = {"http://www.jooq.org", "jOOQ version:3.10.1"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class DistributordirectoriesRecord extends UpdatableRecordImpl<DistributordirectoriesRecord>
		implements Record8<Integer, Integer, String, String, String, Timestamp, Timestamp, Timestamp> {

	private static final long serialVersionUID = 1940858977;

	/**
	 * Create a detached DistributordirectoriesRecord
	 */
	public DistributordirectoriesRecord() {
		super(Distributordirectories.DISTRIBUTORDIRECTORIES);
	}

	/**
	 * Create a detached, initialised DistributordirectoriesRecord
	 */
	public DistributordirectoriesRecord(Integer id, Integer parentdir, String remoteid, String title, String path, Timestamp datecreated, Timestamp dateupdated, Timestamp datedeleted) {
		super(Distributordirectories.DISTRIBUTORDIRECTORIES);

		set(0, id);
		set(1, parentdir);
		set(2, remoteid);
		set(3, title);
		set(4, path);
		set(5, datecreated);
		set(6, dateupdated);
		set(7, datedeleted);
	}

	/**
	 * Getter for <code>thehoard.distributorDirectories.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>thehoard.distributorDirectories.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>thehoard.distributorDirectories.parentDir</code>.
	 */
	public Integer getParentdir() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>thehoard.distributorDirectories.parentDir</code>.
	 */
	public void setParentdir(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>thehoard.distributorDirectories.remoteId</code>.
	 */
	public String getRemoteid() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>thehoard.distributorDirectories.remoteId</code>.
	 */
	public void setRemoteid(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>thehoard.distributorDirectories.title</code>.
	 */
	public String getTitle() {
		return (String) get(3);
	}

	/**
	 * Setter for <code>thehoard.distributorDirectories.title</code>.
	 */
	public void setTitle(String value) {
		set(3, value);
	}

	/**
	 * Getter for <code>thehoard.distributorDirectories.path</code>.
	 */
	public String getPath() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>thehoard.distributorDirectories.path</code>.
	 */
	public void setPath(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>thehoard.distributorDirectories.dateCreated</code>.
	 */
	public Timestamp getDatecreated() {
		return (Timestamp) get(5);
	}

	/**
	 * Setter for <code>thehoard.distributorDirectories.dateCreated</code>.
	 */
	public void setDatecreated(Timestamp value) {
		set(5, value);
	}

	/**
	 * Getter for <code>thehoard.distributorDirectories.dateUpdated</code>.
	 */
	public Timestamp getDateupdated() {
		return (Timestamp) get(6);
	}

	/**
	 * Setter for <code>thehoard.distributorDirectories.dateUpdated</code>.
	 */
	public void setDateupdated(Timestamp value) {
		set(6, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>thehoard.distributorDirectories.dateDeleted</code>.
	 */
	public Timestamp getDatedeleted() {
		return (Timestamp) get(7);
	}

	// -------------------------------------------------------------------------
	// Record8 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>thehoard.distributorDirectories.dateDeleted</code>.
	 */
	public void setDatedeleted(Timestamp value) {
		set(7, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, String, String, String, Timestamp, Timestamp, Timestamp> fieldsRow() {
		return (Row8) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row8<Integer, Integer, String, String, String, Timestamp, Timestamp, Timestamp> valuesRow() {
		return (Row8) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Distributordirectories.DISTRIBUTORDIRECTORIES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Distributordirectories.DISTRIBUTORDIRECTORIES.PARENTDIR;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Distributordirectories.DISTRIBUTORDIRECTORIES.REMOTEID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field4() {
		return Distributordirectories.DISTRIBUTORDIRECTORIES.TITLE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field5() {
		return Distributordirectories.DISTRIBUTORDIRECTORIES.PATH;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field6() {
		return Distributordirectories.DISTRIBUTORDIRECTORIES.DATECREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field7() {
		return Distributordirectories.DISTRIBUTORDIRECTORIES.DATEUPDATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field8() {
		return Distributordirectories.DISTRIBUTORDIRECTORIES.DATEDELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component2() {
		return getParentdir();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component3() {
		return getRemoteid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component4() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component5() {
		return getPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp component6() {
		return getDatecreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp component7() {
		return getDateupdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp component8() {
		return getDatedeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getParentdir();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getRemoteid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value4() {
		return getTitle();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value5() {
		return getPath();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value6() {
		return getDatecreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value7() {
		return getDateupdated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value8() {
		return getDatedeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributordirectoriesRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributordirectoriesRecord value2(Integer value) {
		setParentdir(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributordirectoriesRecord value3(String value) {
		setRemoteid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributordirectoriesRecord value4(String value) {
		setTitle(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributordirectoriesRecord value5(String value) {
		setPath(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributordirectoriesRecord value6(Timestamp value) {
		setDatecreated(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributordirectoriesRecord value7(Timestamp value) {
		setDateupdated(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributordirectoriesRecord value8(Timestamp value) {
		setDatedeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public DistributordirectoriesRecord values(Integer value1, Integer value2, String value3, String value4, String value5, Timestamp value6, Timestamp value7, Timestamp value8) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		value6(value6);
		value7(value7);
		value8(value8);
		return this;
	}
}
