/*
 * This file is generated by jOOQ.
 */
package com.atherapp.common.database.jooq.tables.records;


import com.atherapp.common.database.jooq.tables.Homes;
import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;
import java.sql.Timestamp;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {"http://www.jooq.org", "jOOQ version:3.10.1"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class HomesRecord extends UpdatableRecordImpl<HomesRecord>
		implements Record5<Integer, Integer, String, Timestamp, Timestamp> {

	private static final long serialVersionUID = 985439739;

	/**
	 * Create a detached HomesRecord
	 */
	public HomesRecord() {
		super(Homes.HOMES);
	}

	/**
	 * Create a detached, initialised HomesRecord
	 */
	public HomesRecord(Integer id, Integer ownerid, String name, Timestamp datecreated, Timestamp datedeleted) {
		super(Homes.HOMES);

		set(0, id);
		set(1, ownerid);
		set(2, name);
		set(3, datecreated);
		set(4, datedeleted);
	}

	/**
	 * Getter for <code>thehoard.Homes.id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>thehoard.Homes.id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>thehoard.Homes.ownerId</code>.
	 */
	public Integer getOwnerid() {
		return (Integer) get(1);
	}

	/**
	 * Setter for <code>thehoard.Homes.ownerId</code>.
	 */
	public void setOwnerid(Integer value) {
		set(1, value);
	}

	/**
	 * Getter for <code>thehoard.Homes.name</code>.
	 */
	public String getName() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>thehoard.Homes.name</code>.
	 */
	public void setName(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>thehoard.Homes.dateCreated</code>.
	 */
	public Timestamp getDatecreated() {
		return (Timestamp) get(3);
	}

	/**
	 * Setter for <code>thehoard.Homes.dateCreated</code>.
	 */
	public void setDatecreated(Timestamp value) {
		set(3, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>thehoard.Homes.dateDeleted</code>.
	 */
	public Timestamp getDatedeleted() {
		return (Timestamp) get(4);
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>thehoard.Homes.dateDeleted</code>.
	 */
	public void setDatedeleted(Timestamp value) {
		set(4, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, Timestamp, Timestamp> fieldsRow() {
		return (Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Row5<Integer, Integer, String, Timestamp, Timestamp> valuesRow() {
		return (Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field1() {
		return Homes.HOMES.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Integer> field2() {
		return Homes.HOMES.OWNERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<String> field3() {
		return Homes.HOMES.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field4() {
		return Homes.HOMES.DATECREATED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Field<Timestamp> field5() {
		return Homes.HOMES.DATEDELETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer component2() {
		return getOwnerid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String component3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp component4() {
		return getDatecreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp component5() {
		return getDatedeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Integer value2() {
		return getOwnerid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public String value3() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value4() {
		return getDatecreated();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Timestamp value5() {
		return getDatedeleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HomesRecord value1(Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HomesRecord value2(Integer value) {
		setOwnerid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HomesRecord value3(String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HomesRecord value4(Timestamp value) {
		setDatecreated(value);
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HomesRecord value5(Timestamp value) {
		setDatedeleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public HomesRecord values(Integer value1, Integer value2, String value3, Timestamp value4, Timestamp value5) {
		value1(value1);
		value2(value2);
		value3(value3);
		value4(value4);
		value5(value5);
		return this;
	}
}
