/*
 * This file is generated by jOOQ.
 */
package com.atherapp.common.database.jooq.tables.records;


import com.atherapp.common.database.jooq.tables.Mediastreams;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(value = {"http://www.jooq.org", "jOOQ version:3.10.1"}, comments = "This class is generated by jOOQ")
@SuppressWarnings({"all", "unchecked", "rawtypes"})
public class MediastreamsRecord extends UpdatableRecordImpl<MediastreamsRecord> {

	private static final long serialVersionUID = -1386210690;

	/**
	 * Create a detached MediastreamsRecord
	 */
	public MediastreamsRecord() {
		super(Mediastreams.MEDIASTREAMS);
	}

	/**
	 * Create a detached, initialised MediastreamsRecord
	 */
	public MediastreamsRecord(Integer id, String uuid, String mediafileuuid, Short index, String codecname, String profile, Byte codectype, Double codectimebase, Integer width, Integer height, Double aspectratio, String pixelformat, Integer bitdepth, Integer level, Integer referenceframes, Double averageframerate, Double timebase, Integer bitrate, Boolean isdefault, Boolean isforced, Boolean isexternal, String language, String title, Integer duration, Integer samplerate, Integer channels, String channellayout) {
		super(Mediastreams.MEDIASTREAMS);

		set(0, id);
		set(1, uuid);
		set(2, mediafileuuid);
		set(3, index);
		set(4, codecname);
		set(5, profile);
		set(6, codectype);
		set(7, codectimebase);
		set(8, width);
		set(9, height);
		set(10, aspectratio);
		set(11, pixelformat);
		set(12, bitdepth);
		set(13, level);
		set(14, referenceframes);
		set(15, averageframerate);
		set(16, timebase);
		set(17, bitrate);
		set(18, isdefault);
		set(19, isforced);
		set(20, isexternal);
		set(21, language);
		set(22, title);
		set(23, duration);
		set(24, samplerate);
		set(25, channels);
		set(26, channellayout);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.Id</code>.
	 */
	public Integer getId() {
		return (Integer) get(0);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.Id</code>.
	 */
	public void setId(Integer value) {
		set(0, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.Uuid</code>.
	 */
	public String getUuid() {
		return (String) get(1);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.Uuid</code>.
	 */
	public void setUuid(String value) {
		set(1, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.MediaFileUuid</code>.
	 */
	public String getMediafileuuid() {
		return (String) get(2);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.MediaFileUuid</code>.
	 */
	public void setMediafileuuid(String value) {
		set(2, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.Index</code>.
	 */
	public Short getIndex() {
		return (Short) get(3);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.Index</code>.
	 */
	public void setIndex(Short value) {
		set(3, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.CodecName</code>.
	 */
	public String getCodecname() {
		return (String) get(4);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.CodecName</code>.
	 */
	public void setCodecname(String value) {
		set(4, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.Profile</code>.
	 */
	public String getProfile() {
		return (String) get(5);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.Profile</code>.
	 */
	public void setProfile(String value) {
		set(5, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.CodecType</code>.
	 */
	public Byte getCodectype() {
		return (Byte) get(6);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.CodecType</code>.
	 */
	public void setCodectype(Byte value) {
		set(6, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.CodecTimeBase</code>.
	 */
	public Double getCodectimebase() {
		return (Double) get(7);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.CodecTimeBase</code>.
	 */
	public void setCodectimebase(Double value) {
		set(7, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.Width</code>.
	 */
	public Integer getWidth() {
		return (Integer) get(8);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.Width</code>.
	 */
	public void setWidth(Integer value) {
		set(8, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.Height</code>.
	 */
	public Integer getHeight() {
		return (Integer) get(9);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.Height</code>.
	 */
	public void setHeight(Integer value) {
		set(9, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.AspectRatio</code>.
	 */
	public Double getAspectratio() {
		return (Double) get(10);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.AspectRatio</code>.
	 */
	public void setAspectratio(Double value) {
		set(10, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.PixelFormat</code>.
	 */
	public String getPixelformat() {
		return (String) get(11);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.PixelFormat</code>.
	 */
	public void setPixelformat(String value) {
		set(11, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.BitDepth</code>.
	 */
	public Integer getBitdepth() {
		return (Integer) get(12);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.BitDepth</code>.
	 */
	public void setBitdepth(Integer value) {
		set(12, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.Level</code>.
	 */
	public Integer getLevel() {
		return (Integer) get(13);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.Level</code>.
	 */
	public void setLevel(Integer value) {
		set(13, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.ReferenceFrames</code>.
	 */
	public Integer getReferenceframes() {
		return (Integer) get(14);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.ReferenceFrames</code>.
	 */
	public void setReferenceframes(Integer value) {
		set(14, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.AverageFrameRate</code>.
	 */
	public Double getAverageframerate() {
		return (Double) get(15);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.AverageFrameRate</code>.
	 */
	public void setAverageframerate(Double value) {
		set(15, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.TimeBase</code>.
	 */
	public Double getTimebase() {
		return (Double) get(16);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.TimeBase</code>.
	 */
	public void setTimebase(Double value) {
		set(16, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.BitRate</code>.
	 */
	public Integer getBitrate() {
		return (Integer) get(17);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.BitRate</code>.
	 */
	public void setBitrate(Integer value) {
		set(17, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.IsDefault</code>.
	 */
	public Boolean getIsdefault() {
		return (Boolean) get(18);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.IsDefault</code>.
	 */
	public void setIsdefault(Boolean value) {
		set(18, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.IsForced</code>.
	 */
	public Boolean getIsforced() {
		return (Boolean) get(19);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.IsForced</code>.
	 */
	public void setIsforced(Boolean value) {
		set(19, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.IsExternal</code>.
	 */
	public Boolean getIsexternal() {
		return (Boolean) get(20);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.IsExternal</code>.
	 */
	public void setIsexternal(Boolean value) {
		set(20, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.Language</code>.
	 */
	public String getLanguage() {
		return (String) get(21);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.Language</code>.
	 */
	public void setLanguage(String value) {
		set(21, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.Title</code>.
	 */
	public String getTitle() {
		return (String) get(22);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.Title</code>.
	 */
	public void setTitle(String value) {
		set(22, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.Duration</code>.
	 */
	public Integer getDuration() {
		return (Integer) get(23);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.Duration</code>.
	 */
	public void setDuration(Integer value) {
		set(23, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.SampleRate</code>.
	 */
	public Integer getSamplerate() {
		return (Integer) get(24);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.SampleRate</code>.
	 */
	public void setSamplerate(Integer value) {
		set(24, value);
	}

	/**
	 * Getter for <code>thehoard.MediaStreams.Channels</code>.
	 */
	public Integer getChannels() {
		return (Integer) get(25);
	}

	/**
	 * Setter for <code>thehoard.MediaStreams.Channels</code>.
	 */
	public void setChannels(Integer value) {
		set(25, value);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * Getter for <code>thehoard.MediaStreams.ChannelLayout</code>.
	 */
	public String getChannellayout() {
		return (String) get(26);
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Setter for <code>thehoard.MediaStreams.ChannelLayout</code>.
	 */
	public void setChannellayout(String value) {
		set(26, value);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Record1<Integer> key() {
		return (Record1) super.key();
	}
}
