/*
 * This file is generated by jOOQ.
*/
package com.atherapp.common.database.jooq.tables.records;


import java.sql.Timestamp;

import javax.annotation.Generated;

import com.atherapp.common.database.jooq.tables.Users;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.1"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UsersRecord extends UpdatableRecordImpl<UsersRecord> implements Record8<Integer, String, String, Boolean, String, String, Timestamp, Timestamp> {

    private static final long serialVersionUID = 1730193576;

    /**
     * Setter for <code>thehoard.Users.Id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>thehoard.Users.Id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>thehoard.Users.Name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>thehoard.Users.Name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>thehoard.Users.Email</code>.
     */
    public void setEmail(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>thehoard.Users.Email</code>.
     */
    public String getEmail() {
        return (String) get(2);
    }

    /**
     * Setter for <code>thehoard.Users.IsActive</code>.
     */
    public void setIsactive(Boolean value) {
        set(3, value);
    }

    /**
     * Getter for <code>thehoard.Users.IsActive</code>.
     */
    public Boolean getIsactive() {
        return (Boolean) get(3);
    }

    /**
     * Setter for <code>thehoard.Users.PasswordHash</code>.
     */
    public void setPasswordhash(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>thehoard.Users.PasswordHash</code>.
     */
    public String getPasswordhash() {
        return (String) get(4);
    }

    /**
     * Setter for <code>thehoard.Users.PasswordSalt</code>.
     */
    public void setPasswordsalt(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>thehoard.Users.PasswordSalt</code>.
     */
    public String getPasswordsalt() {
        return (String) get(5);
    }

    /**
     * Setter for <code>thehoard.Users.DateCreated</code>.
     */
    public void setDatecreated(Timestamp value) {
        set(6, value);
    }

    /**
     * Getter for <code>thehoard.Users.DateCreated</code>.
     */
    public Timestamp getDatecreated() {
        return (Timestamp) get(6);
    }

    /**
     * Setter for <code>thehoard.Users.DateUpdated</code>.
     */
    public void setDateupdated(Timestamp value) {
        set(7, value);
    }

    /**
     * Getter for <code>thehoard.Users.DateUpdated</code>.
     */
    public Timestamp getDateupdated() {
        return (Timestamp) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Boolean, String, String, Timestamp, Timestamp> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<Integer, String, String, Boolean, String, String, Timestamp, Timestamp> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Users.USERS.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Users.USERS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Users.USERS.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Boolean> field4() {
        return Users.USERS.ISACTIVE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Users.USERS.PASSWORDHASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Users.USERS.PASSWORDSALT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field7() {
        return Users.USERS.DATECREATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Timestamp> field8() {
        return Users.USERS.DATEUPDATED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean component4() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getPasswordhash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getPasswordsalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component7() {
        return getDatecreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp component8() {
        return getDateupdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Boolean value4() {
        return getIsactive();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getPasswordhash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getPasswordsalt();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value7() {
        return getDatecreated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Timestamp value8() {
        return getDateupdated();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value3(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value4(Boolean value) {
        setIsactive(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value5(String value) {
        setPasswordhash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value6(String value) {
        setPasswordsalt(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value7(Timestamp value) {
        setDatecreated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord value8(Timestamp value) {
        setDateupdated(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UsersRecord values(Integer value1, String value2, String value3, Boolean value4, String value5, String value6, Timestamp value7, Timestamp value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UsersRecord
     */
    public UsersRecord() {
        super(Users.USERS);
    }

    /**
     * Create a detached, initialised UsersRecord
     */
    public UsersRecord(Integer id, String name, String email, Boolean isactive, String passwordhash, String passwordsalt, Timestamp datecreated, Timestamp dateupdated) {
        super(Users.USERS);

        set(0, id);
        set(1, name);
        set(2, email);
        set(3, isactive);
        set(4, passwordhash);
        set(5, passwordsalt);
        set(6, datecreated);
        set(7, dateupdated);
    }
}
